### PR TITLE
LOG-6155: modify multiline detect exception transform to config message_key

### PR DESCRIPTION
**Pull request by jcantrill**
This PR:
* modifies the multiline exception  transform to add a configurable 'message_key'

Ref: https://issues.redhat.com/browse/LOG-6155

Rebase against 6.1 once #180 merges

/hold

cc @syedriko @vparfonov @vimalk78

### CODE REVIEW

**Comment by syedriko** [comment]
@jcantrill It works, but I'm wondering if it goes against the spirit of "field by meaning" from https://github.com/vectordotdev/vector/pull/17668#discussion_r1761846388.

**Comment by jcantrill** [comment]
> @jcantrill It works, but I'm wondering if it goes against the spirit of "field by meaning" from [vectordotdev#17668 (comment)](https://github.com/vectordotdev/vector/pull/17668#discussion_r1761846388).

If I interpret this correctly, it fundamentally creates an abstract to a field value to allow consuming code to be agnostic of the source. I don't see exactly how would apply.  We are adding a config point based upon the structure we know.  We are already setting config for the grouping statements.

**Pull request merged**
