### PR TITLE
fix(security): LOG-2552 Investigate the changes required to make Vector use OpenSSL

### PR DESCRIPTION
**Pull request by syedriko**
[LOG-2552](https://issues.redhat.com//browse/LOG-2552): [spike] Investigate the changes required to make Vector use OpenSSL
For FIPS compliance, make sure
- all crypto is done in OpenSSL
- OpenSSL is linked dynamically

Commits are separate for ease of review and will be sqwashed before merge.

### CODE REVIEW

**Comment by jcantrill** [comment]
@syedriko I assume this is mostly vendored code with strategic changes to make openssl work.  Have you submitted upstream patches?

**Comment by vimalk78** [comment]
/lgtm
able to build ppc image locally. ring does not get built.

**Comment by vimalk78** [comment]
merging the PR to unblock builds
will add another PR to fix the three failing `Cross` test suites. These are failing for a missing file

**Pull request merged**
