### PR TITLE
LOG-5647: Vector syslog output for RFC3164 has extra space that does not comply with spec

### PR DESCRIPTION
**Pull request by syedriko**
Removed an extra space incorrectly inserted between PRI and TIMESTAMP for syslog RFC 3164 output.
Added syslog preamble tests for RFC 3164 and RFC 5424.

## Links
- Depends on PRs: https://github.com/openshift/cluster-logging-operator/pull/2549
- JIRA:
https://issues.redhat.com/browse/LOG-5647

### CODE REVIEW

**Review by jcantrill — COMMENTED** [review]
/approve
/lgtm

**Comment by syedriko** [comment]
https://github.com/openshift/cluster-logging-operator/pull/2549 has to merge for the ci/prow/clo-functional test to pass.

**Pull request merged**
